FROM jenkins/jenkins:lts-jdk17

USER root

# --- Docker CLI (host motorunu kullanmak icin) ---
RUN apt-get update && \
    apt-get install -y ca-certificates curl gnupg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo $VERSION_CODENAME) stable" \
      > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    rm -rf /var/lib/apt/lists/*

# --- Ansible + Python (YENI KATMAN) ---
# Ansible pipx setup; and docke
# Ansible container yonetebilsin (community.docker)
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv sshpass && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --break-system-packages ansible docker && \
    ansible-galaxy collection install community.docker

USER jenkins